In [3]:
!pip3 install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.8 MB 2.0 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.8 MB 1.9 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 2.1 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.8 MB 2.1 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.8 MB 2.1 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.8 MB 2.1 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.8 MB 2.2 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.8 MB 2.2 MB/s eta 0:00:04
   -------------- ------------------------- 4.7/12.8 MB 2.2 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.8 MB 2.3 MB/s eta 0:00:04
   ----------

In [2]:
import time
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
size=1_000_000
py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"python list time {end-start}")

np_arr=np.array(py_list)
start=time.time()
sq_list=np_arr**2
end=time.time()
print(f"python list time {end-start}")


python list time 0.12572932243347168
python list time 0.015077590942382812


In [5]:
import sys

print(f"python list size={sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"numpy list size={np_arr.nbytes} bytes")

python list size=8000056000000 bytes
numpy list size=8000000 bytes


In [6]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.shape)

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2d,arr2d.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [30]:
arr1=np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)
print()

arr2=np.ones((5,2))
print(arr2,arr2.shape)
print()

arr3=np.full((2,3),100)
print(arr3,arr3.shape)
print()

arr4=np.eye((5))
print(arr4,arr4.shape)
print()

arr5=np.arange(1,21,2).reshape(2,5)
print(arr5,arr5.shape)
print()

new_arr=arr5.astype(float)
print(new_arr)
print()

arr6=np.linspace(1,10,3)
print(arr6,arr6.shape)



[[0 0 0]
 [0 0 0]] (2, 3)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] (5, 2)

[[100 100 100]
 [100 100 100]] (2, 3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)

[[ 1  3  5  7  9]
 [11 13 15 17 19]] (2, 5)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]]

[ 1.   5.5 10. ] (3,)


In [35]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"shape of array {arr.shape}\n")
print(f"size of array {arr.size}\n")
print(f"data type of array {arr.dtype}\n")
print(f"dimension of array {arr.ndim}\n")
print(f"size of array {arr.size}\n")
print(f"type cast \n {arr} to \n{arr.astype(np.float64)}")

shape of array (3, 3)

size of array 9

data type of array int64

dimension of array 2

size of array 9

type cast 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] to 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [40]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape,"\n")

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape,"\n")

flattened=arr.flatten()
print(flattened,flattened.shape,"\n")

[[1 2 3]
 [4 5 6]] (2, 3) 

[[1 2]
 [3 4]
 [5 6]] (3, 2) 

[1 2 3 4 5 6] (6,) 



In [50]:
#1d array
arr=np.array([1,2,3,4,5])
print(arr[3])

#2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(f"2d array- {arr2[1][2]}")

#fancy indexing
idx=[0,1,3]
print(f"fancing indexing: {arr[idx]}")

#boolean indexing
print(f"boolean indexing: {arr[arr%2==0]}")

#slicing index
print(arr[1:4])
print(arr[-1:-4:-1])

4
2d array- 6
fancing indexing: [1 2 4]
boolean indexing: [2 4]
[2 3 4]
[5 4 3]


In [52]:
#copy in python list
nums=([1,2,3,4,5])
sub_list=nums[1:3]
print(f"sublist: {sub_list}")
sub_list[0]=200
print(f"sublist: {sub_list}")
print(nums)

#view in numpy
num_arr=np.array([1,2,3,4,5])
sub_arr=num_arr[1:3]
print(f"subarray: {sub_arr}")
sub_arr[0]=200
print(f"subarray: {sub_arr}")
print(num_arr)

#copy in numpy
num_arr2=np.array([1,2,3,4,5])
copy_arr=num_arr2[1:3].copy()
print(f"subarray through copy: {copy_arr}")
copy_arr[0]=200
print(f"subarray copy: {copy_arr}")
print(num_arr2)

sublist: [2, 3]
sublist: [200, 3]
[1, 2, 3, 4, 5]
subarray: [2 3]
subarray: [200   3]
[  1 200   3   4   5]
subarray through copy: [2 3]
subarray copy: [200   3]
[1 2 3 4 5]


In [54]:
arr=np.array([1+3j])
print(arr,arr.dtype)

[1.+3.j] complex128


In [56]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))
sum_of_col=np.sum(arr2d,axis=0)
print(sum_of_col)
sum_of_row=np.sum(arr2d,axis=1)
print(sum_of_row)

print(arr2d[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [70]:
#3d array
#12  78
#34  98
#56  1011
arr3d=np.array([[[1,2,10],[3,4,10],[5,6,10]],[[7,6,10],[8,9,10],[10,11,10]]]) #2x2x3

print(arr3d,arr3d.shape)
#indexing
print(f"indexing {arr3d[0,1,1]}")

#slicing
print(f"slicing {arr3d[:,0:2,1:]}")



[[[ 1  2 10]
  [ 3  4 10]
  [ 5  6 10]]

 [[ 7  6 10]
  [ 8  9 10]
  [10 11 10]]] (2, 3, 3)
indexing 4
slicing [[[ 2 10]
  [ 4 10]]

 [[ 6 10]
  [ 9 10]]]


In [76]:
#12   1
#34 + 3
#56   5

arr1=np.array([[1,2],[3,4],[5,6]]) #3x2
arr2=np.array([[1],[3],[5]]) #3x1
print(arr1+arr2)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [81]:
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
print(f"mean: {mean}")
std_dev=np.std(arr)
print(f"standard_deviation: {std_dev}")
print(f"normalization:\n {(arr-mean)/std_dev}")

mean: 2.5
standard_deviation: 1.118033988749895
normalization:
 [[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [87]:
arr=np.array([[1,2],[3,4]])
print(f"Max: {np.max(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Sum: {np.sum(arr)}")
print(f"Product: {np.prod(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Std: {np.std(arr)}")
print(f"var: {np.var(arr)}")
print(f"median: {np.median(arr)}")
print(f"argmin: {np.argmin(arr)}")
print(f"argmax: {np.argmax(arr)}")
print()
print(f"power:\n {np.pow(arr,3)}")
print(f"sqrt:\n  {np.sqrt(arr)}")
print(f"square:\n  {np.square(arr)}")
print()
print(f"log:\n  {np.log(arr)}")
print(f"log10:\n  {np.log10(arr)}")
print(f"log2:\n  {np.log2(arr)}")
print(f"exp:\n  {np.exp(arr)}")
print()
arr1=np.array([-1.23,4,4,5.7,8.99,7.90])
print(f"round:\n  {np.round(arr1)}")
print(f"floor:\n  {np.floor(arr1)}")
print(f"ceil:\n  {np.ceil(arr1)}")
print(f"truncate:\n  {np.trunc(arr1)}")
print(f"uniuqe:\n  {np.unique(arr1)}")
print(f"sort:\n  {np.sort(arr1)}")
print(f"abs:\n  {np.abs(arr1)}")

Max: 4
Min: 1
Sum: 10
Product: 24
Mean: 2.5
Std: 1.118033988749895
var: 1.25
median: 2.5
argmin: 0
argmax: 3

power:
 [[ 1  8]
 [27 64]]
sqrt:
  [[1.         1.41421356]
 [1.73205081 2.        ]]
square:
  [[ 1  4]
 [ 9 16]]

log:
  [[0.         0.69314718]
 [1.09861229 1.38629436]]
log10:
  [[0.         0.30103   ]
 [0.47712125 0.60205999]]
log2:
  [[0.        1.       ]
 [1.5849625 2.       ]]
exp:
  [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

round:
  [-1.  4.  4.  6.  9.  8.]
floor:
  [-2.  4.  4.  5.  8.  7.]
ceil:
  [-1.  4.  4.  6.  9.  8.]
truncate:
  [-1.  4.  4.  5.  8.  7.]
uniuqe:
  [-1.23  4.    5.7   7.9   8.99]
sort:
  [-1.23  4.    4.    5.7   7.9   8.99]
abs:
  [1.23 4.   4.   5.7  8.99 7.9 ]
