In [1]:
import torch
import torch.nn as nn

In [15]:
#input
torch.manual_seed(42)
input=torch.tensor([1.0,2.0,3.0])

In [16]:
neuron=nn.Linear(in_features=3,out_features=1)

In [17]:
output=neuron(input)

In [18]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [19]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [20]:
neuron.weight @input + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)